# Generated by Django 4.0 on 2021-12-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='כמות'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.CharField(max_length=100, verbose_name='פריט'),
        ),
    ]
