# Generated by Django 4.0 on 2021-12-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_alter_stock_amount_alter_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.CharField(choices=[('beds', 'מיטות'), ('bowls', 'קערות'), ('cups', 'כוסות'), ('snacks', 'חטיפים'), ('toys', 'צעצועים'), ('straps', 'רצועות'), ('sandbags', 'שקי חול'), ('collar', 'קולרים'), ('cleaning brushes', 'מברשות ניקוי'), ('dry dog food', 'מזון יבש לכלבים'), ('dry cat food', 'מזון יבש לחתולים'), ('fences', 'גדרות')], max_length=100, verbose_name='פריט'),
        ),
    ]
