# Generated by Django 4.0 on 2022-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_alter_stock_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'מלאי'},
        ),
    ]
