# Generated by Django 3.2.9 on 2021-12-23 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='תאריך '),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=100, verbose_name='שם המדווח '),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, verbose_name='תוכן הדיווח '),
        ),
    ]
