# Generated by Django 4.0 on 2021-12-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_discussion_discuss_alter_discussion_forum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(default=None, max_length=1000, verbose_name='התגובה'),
        ),
    ]
