# Generated by Django 4.0 on 2021-12-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_discussion_discuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='שם'),
        ),
    ]
