# Generated by Django 4.0 on 2022-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_discussion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(blank=True, default=None, max_length=5000, verbose_name='התגובה'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='תיאור'),
        ),
    ]
