# Generated by Django 3.2.9 on 2021-12-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=5000)),
                ('type', models.CharField(choices=[('cat', 'חתול'), ('dog', 'כלב')], max_length=10, verbose_name='סוג')),
                ('genre', models.CharField(choices=[('adoption', 'אימוץ'), ('info', 'מידע'), ('training', 'אילוף'), ('other', 'אחר')], default='other', max_length=200, verbose_name="ז'אנר")),
                ('link', models.CharField(default=None, max_length=2000)),
            ],
        ),
    ]
