# Generated by Django 4.0 on 2022-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'מאמרים'},
        ),
    ]
