# Generated by Django 4.0 on 2021-12-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='סכום'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='credit_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='מספר אשראי'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='cvc',
            field=models.CharField(blank=True, max_length=100, verbose_name='3 ספרות מאחורי הכרטיס'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='id_number',
            field=models.CharField(max_length=100, verbose_name='תעודת זהות'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='name',
            field=models.CharField(max_length=100, verbose_name='שם'),
        ),
    ]
