# Generated by Django 4.0 on 2022-01-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0002_alter_donations_amount_alter_donations_credit_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name_plural': 'Donations'},
        ),
    ]
