# Generated by Django 4.0 on 2022-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0003_alter_donations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name_plural': 'תרומות'},
        ),
    ]
