# Generated by Django 4.0 on 2022-01-03 11:41

import Animal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('submitter', models.CharField(max_length=100, null=True, verbose_name='הוכנס על ידי')),
                ('species', models.CharField(choices=[('dog', 'כלב'), ('cat', 'חתול')], default='Dog', max_length=30, verbose_name='סוג')),
                ('breed', models.CharField(max_length=30, verbose_name='גזע')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('sex', models.CharField(choices=[('M', 'זכר'), ('F', 'נקבה')], default='M', max_length=30, verbose_name='מין')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='תאריך קליטה')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='Animal', verbose_name='העלאת תמונה')),
                ('Adoption', models.CharField(choices=[('N', 'לא'), ('Y', 'כן')], default='No', max_length=30, verbose_name='מוכן לאימוץ')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.IntegerField(blank=True, default=0)),
                ('deleted', models.IntegerField(blank=True, default=0)),
                ('current', models.IntegerField(blank=True, default=0)),
                ('month', models.IntegerField(blank=True, default=1, validators=[Animal.models.validate_month])),
            ],
            options={
                'verbose_name_plural': 'stats',
            },
        ),
    ]
