# Generated by Django 4.0 on 2022-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'מאגר בעלי חיים'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'סטטיסטיקה'},
        ),
    ]
