# Generated by Django 4.0 on 2022-01-03 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_task',
            options={'verbose_name_plural': 'לוח מטלות'},
        ),
        migrations.AlterField(
            model_name='list_task',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='list_task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='כותרת'),
        ),
        migrations.AlterField(
            model_name='list_task',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='תיאור'),
        ),
    ]
