# Generated by Django 3.2.9 on 2021-12-23 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='תאריך '),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='entrance_time',
            field=models.TimeField(verbose_name='שעת כניסה '),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leaving_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='שעת יציאה '),
        ),
    ]
