# Generated by Django 4.0 on 2022-01-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20211223_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entrance_time',
            field=models.TimeField(default=None, verbose_name='שעת כניסה '),
        ),
    ]
