# Generated by Django 4.0 on 2022-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierregistration',
            options={'verbose_name_plural': 'ספקים'},
        ),
    ]
